import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import worker from '../api/worker.js';
const origin='https://drop-public-media.anon69f.chatgpt.site';
const owner={'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'owner@example.test',Origin:origin,'Content-Type':'application/json'};
const records=new Map(),bytes=crypto.getRandomValues(new Uint8Array(32));
const env={DROP_OWNER_EMAIL:'owner@example.test',B2_SETTINGS_ENCRYPTION_KEY:Buffer.from(bytes).toString('base64'),SETTINGS:{get:async k=>records.has(k)?{json:async()=>JSON.parse(records.get(k))}:null,put:async(k,v)=>records.set(k,v)}};
const key=await crypto.subtle.importKey('raw',bytes,'AES-GCM',false,['encrypt']);
const iv=crypto.getRandomValues(new Uint8Array(12));
const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode('private/b2-settings-v1')},key,new TextEncoder().encode(JSON.stringify({keyId:'test',applicationKey:'test-secret',bucketId:'bucket'})));
records.set('private/b2-settings-v1',JSON.stringify({iv:Buffer.from(iv).toString('base64'),ciphertext:Buffer.from(ciphertext).toString('base64')}));
const uploads=[];let remoteCalls=0;
globalThis.fetch=async(url,init)=>{remoteCalls++;assert.equal(init.redirect,'manual');url=String(url);
 if(url.includes('b2_authorize_account'))return Response.json({accountId:'account',authorizationToken:'auth',apiInfo:{storageApi:{apiUrl:'https://api005.backblazeb2.com',downloadUrl:'https://f005.backblazeb2.com',allowed:{capabilities:['readFiles','listFiles','deleteFiles']}}}});
 if(url.includes('b2_list_buckets'))return Response.json({buckets:[{bucketId:'bucket',bucketType:'allPrivate'}]});
 if(url.includes('b2_get_upload_url'))return Response.json({uploadUrl:'https://pod-test.backblaze.com/upload',authorizationToken:'upload'});
 if(url.includes('b2_download_file_by_id')){assert.equal(init.headers.Authorization,'auth');return new Response(init.method==='HEAD'?null:new Uint8Array([1,2]),{status:init.headers.Range?206:200,headers:{'Content-Type':'image/jpeg','Content-Length':'2',...(init.headers.Range?{'Content-Range':'bytes 0-1/3'}:{})}});}
 if(url.includes('cdninstagram.com'))return new Response(new Uint8Array([1,2,3]),{headers:{'Content-Type':'image/jpeg'}});
 if(url.endsWith('/upload')){uploads.push({name:decodeURIComponent(init.headers['X-Bz-File-Name']),body:init.body});return Response.json({fileId:'id-'+uploads.length});}
 throw Error('Unexpected outbound URL');
};
const items=[0,1].map(i=>({type:'image',url:origin+'/api/media?url='+encodeURIComponent('https://a.cdninstagram.com/'+i+'.jpg')}));
const body={postUrl:'https://www.instagram.com/p/Test123/',items,index:0};
const req=(data=body,headers=owner)=>new Request(origin+'/api/collection/save',{method:'POST',headers,body:JSON.stringify(data)});
assert.equal((await worker.fetch(req(body,{'Content-Type':'application/json'}),env)).status,401);
assert.equal((await worker.fetch(req(body,{...owner,'oai-authenticated-user-email':'other@test.com'}),env)).status,403);
assert.equal((await worker.fetch(req(body,{...owner,Origin:'https://evil.test'}),env)).status,403);
assert.equal(remoteCalls,0);
const malicious={...body,items:[{type:'image',url:origin+'/api/media?url=https://evilcdninstagram.com/a.jpg'}]};
assert.equal((await worker.fetch(req(malicious),env)).status,400);assert.equal(remoteCalls,0);
assert.equal((await worker.fetch(req(),env)).status,200);assert.equal(uploads.length,1);
assert.equal((await worker.fetch(req(),env)).status,200);assert.equal(uploads.length,1,'Retry skips completed item');
const final=await worker.fetch(req({...body,index:1}),env);assert.equal(final.status,200);assert.equal((await final.json()).complete,true);assert.equal(uploads.length,3);
const manifest=JSON.parse(new TextDecoder().decode(uploads[2].body));assert.equal(manifest.items.length,2);assert.equal(manifest.items[0].index,0);assert.equal(manifest.items[1].index,1);assert.ok(!JSON.stringify(manifest).includes('cdninstagram'));assert.ok(!JSON.stringify(manifest).includes('test-secret'));
await worker.fetch(req(),env);assert.equal(uploads.length,3,'Completed post is not duplicated');
const page=await worker.fetch(new Request(origin+'/save',{headers:owner}),env);assert.equal(page.status,200);new Function((await page.text()).match(/<script nonce="[^"]+">([\s\S]*?)<\/script>/)[1]);
const front=await readFile(new URL('../index.html',import.meta.url),'utf8');new Function(front.match(/<script>([\s\S]*?)<\/script>/)[1]);assert.match(front,/resolvedUrl=url/);
console.log('Save authorization, host restrictions, carousel ordering, resume, deduplication and browser script tests passed.');
env.SETTINGS.list=async()=>({objects:[...records.keys()].filter(k=>k.startsWith('collection/')).map(key=>({key})),truncated:false});
const read=(path,headers=owner,method='GET')=>worker.fetch(new Request(origin+path,{headers,method}),env);
assert.equal((await read('/collection',{})).status,302);
assert.equal((await read('/api/collection',{})).status,401);
assert.equal((await read('/api/collection/media?post=Test123&index=0',{})).status,401);
assert.equal((await read('/api/collection',{...owner,'oai-authenticated-user-email':'other@test.com'})).status,403);
const listing=await read('/api/collection');assert.equal(listing.status,200);const list=await listing.json();assert.equal(list.posts.length,1);assert.equal(list.posts[0].items.length,2);assert.ok(!JSON.stringify(list).includes('fileId'));assert.equal(list.cursor,null);
const partial=await read('/api/collection/media?post=Test123&index=0',{...owner,Range:'bytes=0-1'});assert.equal(partial.status,206);assert.equal(partial.headers.get('Content-Range'),'bytes 0-1/3');assert.match(partial.headers.get('Cache-Control'),/no-store/);assert.equal(partial.headers.get('Authorization'),null);assert.equal((await partial.arrayBuffer()).byteLength,2);
const download=await read('/api/collection/media?post=Test123&index=0&download=1');assert.match(download.headers.get('Content-Disposition'),/attachment/);
assert.equal((await read('/api/collection/media?post=Missing&index=0')).status,404);
assert.equal((await read('/api/collection/media?post=Test123&index=9')).status,404);
assert.equal((await read('/api/collection/media?post=Test123&index=0',{...owner,Range:'bytes=1-2,4-5'})).status,416);
const gallery=await read('/collection');assert.equal(gallery.status,200);new Function((await gallery.text()).match(/<script nonce="[^"]+">([\s\S]*?)<\/script>/)[1]);
console.log('Collection privacy, pagination response, saved media, byte ranges, download and gallery script tests passed.');
env.SETTINGS.delete=async key=>records.delete(key);
env.SETTINGS.list=async({prefix})=>({objects:[...records.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key})),truncated:false});
const oldFetch=globalThis.fetch;let foreign=false,failOnce=true;const deleted=[];
let versions=uploads.map((u,i)=>({fileName:u.name,fileId:'id-'+(i+1),action:'upload'}));versions.push({fileName:versions[0].fileName,fileId:'old-version',action:'upload'});
globalThis.fetch=async(url,init)=>{const target=String(url);if(target.includes('b2_list_file_versions')){const body=JSON.parse(init.body);assert.equal(body.prefix,'collection/Test123/');return Response.json({files:foreign?[{fileName:'collection/Other/01.jpg',fileId:'foreign',action:'upload'}]:versions.slice(0,body.maxFileCount)});}if(target.includes('b2_delete_file_version')){if(failOnce&&deleted.length===1){failOnce=false;return Response.json({code:'service_unavailable'},{status:503});}const body=JSON.parse(init.body);deleted.push(body.fileId);versions=versions.filter(f=>f.fileId!==body.fileId);return Response.json(body);}return oldFetch(url,init);};
assert.equal((await read('/api/collection?post=Test123',{},'DELETE')).status,401);
assert.equal((await read('/api/collection?post=Test123',{...owner,Origin:'https://evil.test'},'DELETE')).status,403);
assert.equal((await read('/api/collection?post=../Other',owner,'DELETE')).status,400);
foreign=true;assert.equal((await read('/api/collection?post=Test123',owner,'DELETE')).status,503);assert.equal(deleted.length,0);foreign=false;
assert.equal((await read('/api/collection?post=Test123',owner,'DELETE')).status,503);assert.ok(records.has('collection/Test123/complete'));assert.ok(records.has('collection/Test123/deleting'));
assert.equal((await worker.fetch(req(),env)).status,400,'Save blocked during incomplete removal');
const removed=await read('/api/collection?post=Test123',owner,'DELETE');assert.equal(removed.status,200);assert.equal((await removed.json()).removed,true);assert.equal(versions.length,0);assert.equal(deleted.length,4);assert.ok(records.has('private/b2-settings-v1'));assert.ok(![...records.keys()].some(k=>k.startsWith('collection/Test123/')));
assert.equal((await read('/api/collection?post=Test123',owner,'DELETE')).status,200,'Retry after success is harmless');
console.log('Removal ownership, CSRF, exact prefix, older versions, partial-failure retry and metadata cleanup tests passed.');
